// <auto-generated />
using System;
using BeyondMovement.Infrastructure;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace BeyondMovement.Infrastructure.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260928151741_AddSportsCatalogue")]
    partial class AddSportsCatalogue
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("BeyondMovement.Infrastructure.Auditing.AuditLog", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<Guid?>("ActorUserId")
                        .HasColumnType("uuid");

                    b.Property<string>("Details")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<DateTime>("OccurredAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("ActorUserId");

                    b.HasIndex("OccurredAtUtc");

                    b.ToTable("AuditLogs", (string)null);
                });

            modelBuilder.Entity("BeyondMovement.Modules.Athletes.Domain.AthleteProfile", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("AnonymizedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("CoachId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateOnly?>("DateOfBirth")
                        .HasColumnType("date");

                    b.Property<DateTime?>("DeletedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Gender")
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)");

                    b.Property<bool>("IsLoyal")
                        .HasColumnType("boolean");

                    b.Property<DateTime?>("LoyalSinceUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Notes")
                        .HasMaxLength(4000)
                        .HasColumnType("character varying(4000)");

                    b.Property<Guid?>("SportId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("SportId");

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.HasIndex("CoachId", "DeletedAtUtc");

                    b.ToTable("AthleteProfiles", (string)null);
                });

            modelBuilder.Entity("BeyondMovement.Modules.Athletes.Domain.Sport", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<int>("SortOrder")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("Sports", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("0b6f3c1e-58a2-4d7e-9c41-2f8a6e1d3b70"),
                            Name = "Artistic Swimming",
                            SortOrder = 0
                        },
                        new
                        {
                            Id = new Guid("3d9a5f12-7c4e-4a8b-b1f6-5e2d8c9a0f47"),
                            Name = "Athletics",
                            SortOrder = 0
                        },
                        new
                        {
                            Id = new Guid("8a1c4e7b-2d9f-4e35-a6b8-0f3c7d1e9a52"),
                            Name = "Badminton",
                            SortOrder = 0
                        },
                        new
                        {
                            Id = new Guid("61f7b3d8-4a2c-4e9d-8b5a-3c6e0f9d2a17"),
                            Name = "Basketball",
                            SortOrder = 0
                        },
                        new
                        {
                            Id = new Guid("2e8d6a41-9b3f-4c7e-a5d2-6f1b8c4e3a90"),
                            Name = "Boxing",
                            SortOrder = 0
                        },
                        new
                        {
                            Id = new Guid("9c3f1a6e-5d8b-4b2a-9e7c-4a0d6f2b8e13"),
                            Name = "Cycling",
                            SortOrder = 0
                        },
                        new
                        {
                            Id = new Guid("47b2e9d5-3a6c-4f1e-8d4b-9e5a2c7f0b61"),
                            Name = "Diving",
                            SortOrder = 0
                        },
                        new
                        {
                            Id = new Guid("d5a8c2f7-6e1b-4d93-b7a4-2c9f5e8d1a36"),
                            Name = "Equestrian",
                            SortOrder = 0
                        },
                        new
                        {
                            Id = new Guid("1f4e7b9a-8c2d-4a56-9f3e-7b1d4a6c9e82"),
                            Name = "Fencing",
                            SortOrder = 0
                        },
                        new
                        {
                            Id = new Guid("b8d1f5a3-4e7c-4c29-a8f1-5d3b9e6a2c74"),
                            Name = "Fin Swimming",
                            SortOrder = 0
                        },
                        new
                        {
                            Id = new Guid("5e2c7a94-1f3b-4c86-a0d5-7b9e2c4f1a38"),
                            Name = "Football",
                            SortOrder = 0
                        },
                        new
                        {
                            Id = new Guid("6a9e3d1c-7f5b-4e8a-b2c6-8d4f1a3e7b95"),
                            Name = "Golf",
                            SortOrder = 0
                        },
                        new
                        {
                            Id = new Guid("e2c5a8f1-3b9d-4f7a-8c1e-4b7d2f9a5c63"),
                            Name = "Gymnastics",
                            SortOrder = 0
                        },
                        new
                        {
                            Id = new Guid("73d1b6e9-2a4f-4c8b-9e5d-1f6a3c8b4d27"),
                            Name = "Handball",
                            SortOrder = 0
                        },
                        new
                        {
                            Id = new Guid("a4f8c3e6-9d2b-4a71-b5e8-3c1f7d9a6e48"),
                            Name = "Judo",
                            SortOrder = 0
                        },
                        new
                        {
                            Id = new Guid("0c7e2a9d-5f3b-4d86-a1c4-9e2b5f8d3a16"),
                            Name = "Karate",
                            SortOrder = 0
                        },
                        new
                        {
                            Id = new Guid("58b3f1d7-6c9a-4e2f-8a7d-2e5c9b1f4d83"),
                            Name = "Modern Pentathlon",
                            SortOrder = 0
                        },
                        new
                        {
                            Id = new Guid("c9e6a2d4-1b8f-4f53-9d2a-6b4e8c3f1a57"),
                            Name = "Padel",
                            SortOrder = 0
                        },
                        new
                        {
                            Id = new Guid("24a7d9f3-8e1c-4b6a-a3f9-5c8e2d6b9f10"),
                            Name = "Rowing",
                            SortOrder = 0
                        },
                        new
                        {
                            Id = new Guid("f7b4e1c8-3d6a-4a2e-b9c5-1d7f4a8e2c36"),
                            Name = "Rugby",
                            SortOrder = 0
                        },
                        new
                        {
                            Id = new Guid("3b8f6d2a-9c4e-4e71-8f3b-7a2d5e9c6b84"),
                            Name = "Sailing",
                            SortOrder = 0
                        },
                        new
                        {
                            Id = new Guid("8e2a5c9f-4d7b-4c38-a6e1-9f3b7d2a5c49"),
                            Name = "Shooting",
                            SortOrder = 0
                        },
                        new
                        {
                            Id = new Guid("5d9c1f4b-2e8a-4b67-9c3d-4e8a1f6b9d25"),
                            Name = "Squash",
                            SortOrder = 0
                        },
                        new
                        {
                            Id = new Guid("b1e7a3d6-9f2c-4d85-8b4e-6c2f9a3d7e18"),
                            Name = "Swimming",
                            SortOrder = 0
                        },
                        new
                        {
                            Id = new Guid("46c2f8b9-1a5d-4f3e-a7c2-8d5b3e9f1a64"),
                            Name = "Table Tennis",
                            SortOrder = 0
                        },
                        new
                        {
                            Id = new Guid("da3f9b5e-6c1a-4a28-b3d7-2f9e5c1a8b37"),
                            Name = "Taekwondo",
                            SortOrder = 0
                        },
                        new
                        {
                            Id = new Guid("c4a81e27-9d5f-4b3a-8e6c-1a7d9f2b5e04"),
                            Name = "Tennis",
                            SortOrder = 0
                        },
                        new
                        {
                            Id = new Guid("7f1d4a8c-3e6b-4e92-9a5f-1b4d7c2e8f56"),
                            Name = "Trampoline",
                            SortOrder = 0
                        },
                        new
                        {
                            Id = new Guid("2a6e9c3f-8b1d-4c74-8e2a-5f9c3b6d1e42"),
                            Name = "Triathlon",
                            SortOrder = 0
                        },
                        new
                        {
                            Id = new Guid("9b4c7e1a-5f2d-4b39-a8c6-3e7a1d5f9b28"),
                            Name = "Volleyball",
                            SortOrder = 0
                        },
                        new
                        {
                            Id = new Guid("e5d2b8f4-7a3c-4f16-9b1e-8c4a2f7d3b69"),
                            Name = "Water Polo",
                            SortOrder = 0
                        },
                        new
                        {
                            Id = new Guid("13f8a6c2-4d9e-4a5b-b7f3-9d1c6e4a8f75"),
                            Name = "Weightlifting",
                            SortOrder = 0
                        },
                        new
                        {
                            Id = new Guid("c6a3e9d1-2b7f-4d48-8a5c-7e3f1b9d4a26"),
                            Name = "Wrestling",
                            SortOrder = 0
                        },
                        new
                        {
                            Id = new Guid("f0e9d8c7-2b4a-4f61-9d3e-8c5b7a1e6d29"),
                            Name = "Other",
                            SortOrder = 1
                        });
                });

            modelBuilder.Entity("BeyondMovement.Modules.Finance.Domain.Expense", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<long>("AmountMinor")
                        .HasColumnType("bigint");

                    b.Property<Guid>("CoachId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Currency")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("character varying(3)");

                    b.Property<DateOnly>("IncurredOn")
                        .HasColumnType("date");

                    b.Property<string>("Note")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<uint>("Version")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.HasKey("Id");

                    b.HasIndex("CoachId", "IncurredOn");

                    b.ToTable("Expenses", null, t =>
                        {
                            t.HasCheckConstraint("CK_Expenses_Amount", "\"AmountMinor\" > 0");
                        });
                });

            modelBuilder.Entity("BeyondMovement.Modules.Finance.Domain.PackagePurchase", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("AthleteProfileId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("AthleteUserId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("CoachId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Currency")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("character varying(3)");

                    b.Property<string>("Origin")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("PackageName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<Guid?>("PackageOptionId")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("PaidAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("PaidByUserId")
                        .HasColumnType("uuid");

                    b.Property<long>("PriceMinor")
                        .HasColumnType("bigint");

                    b.Property<Guid?>("PurchasedPackageId")
                        .HasColumnType("uuid");

                    b.Property<int>("SessionCount")
                        .HasColumnType("integer");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<uint>("Version")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.HasKey("Id");

                    b.HasIndex("AthleteProfileId")
                        .IsUnique()
                        .HasDatabaseName("IX_PackagePurchases_OnePendingPerAthlete")
                        .HasFilter("\"Status\" = 'Pending'");

                    b.HasIndex("PackageOptionId");

                    b.HasIndex("PurchasedPackageId")
                        .IsUnique()
                        .HasDatabaseName("IX_PackagePurchases_OnePurchasePerPackage")
                        .HasFilter("\"PurchasedPackageId\" IS NOT NULL");

                    b.HasIndex("AthleteUserId", "CreatedAtUtc");

                    b.HasIndex("CoachId", "Status", "CreatedAtUtc");

                    b.ToTable("PackagePurchases", null, t =>
                        {
                            t.HasCheckConstraint("CK_PackagePurchases_PaidConsistency", "(\"Status\" = 'Paid' AND \"PaidAtUtc\" IS NOT NULL AND \"PurchasedPackageId\" IS NOT NULL) OR (\"Status\" = 'Pending' AND \"PaidAtUtc\" IS NULL AND \"PurchasedPackageId\" IS NULL)");

                            t.HasCheckConstraint("CK_PackagePurchases_Price", "\"PriceMinor\" >= 0");

                            t.HasCheckConstraint("CK_PackagePurchases_SessionCount", "\"SessionCount\" > 0");
                        });
                });

            modelBuilder.Entity("BeyondMovement.Modules.Finance.Domain.PackagePurchaseFeature", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Code")
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)");

                    b.Property<Guid>("PackagePurchaseId")
                        .HasColumnType("uuid");

                    b.Property<int>("Position")
                        .HasColumnType("integer");

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("Id");

                    b.HasIndex("PackagePurchaseId", "Position")
                        .IsUnique();

                    b.ToTable("PackagePurchaseFeatures", (string)null);
                });

            modelBuilder.Entity("BeyondMovement.Modules.Identity.Domain.Invitation", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("CoachId")
                        .HasColumnType("uuid");

                    b.Property<string>("CodeHash")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("CreatedByUserId")
                        .HasColumnType("uuid");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<DateTime>("ExpiresAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("LastSentAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("LastValidatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("RedeemedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("RevokedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("SendCount")
                        .HasColumnType("integer");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("CodeHash")
                        .IsUnique();

                    b.HasIndex("Email")
                        .IsUnique()
                        .HasFilter("\"Status\" = 'Pending'");

                    b.HasIndex("CoachId", "Status");

                    b.ToTable("Invitations", (string)null);
                });

            modelBuilder.Entity("BeyondMovement.Modules.Identity.Domain.PasswordResetToken", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("ExpiresAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("TokenHash")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<DateTime?>("UsedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("TokenHash")
                        .IsUnique();

                    b.HasIndex("UserId");

                    b.ToTable("PasswordResetTokens", (string)null);
                });

            modelBuilder.Entity("BeyondMovement.Modules.Identity.Domain.RefreshToken", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("DeviceId")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<DateTime>("ExpiresAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("FamilyId")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("RevokedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("TokenHash")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<DateTime?>("UsedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("FamilyId");

                    b.HasIndex("TokenHash")
                        .IsUnique();

                    b.HasIndex("UserId");

                    b.ToTable("RefreshTokens", (string)null);
                });

            modelBuilder.Entity("BeyondMovement.Modules.Identity.Domain.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("CoachId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<int>("FailedLoginAttempts")
                        .HasColumnType("integer");

                    b.Property<string>("FullName")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("GoogleSubjectId")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<DateTime?>("LastLoginAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("LockedOutUntilUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("NotificationPreferences")
                        .HasColumnType("jsonb");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("text");

                    b.Property<string>("Phone")
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)");

                    b.Property<DateTime?>("ProfileCompletedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("TimeZone")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<string>("UiPreferences")
                        .HasColumnType("jsonb");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("GoogleSubjectId")
                        .IsUnique()
                        .HasFilter("\"GoogleSubjectId\" IS NOT NULL");

                    b.HasIndex("CoachId", "Role", "Status");

                    b.ToTable("Users", (string)null);
                });

            modelBuilder.Entity("BeyondMovement.Modules.Packages.Domain.AthletePackagePrice", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("AthleteUserId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("PackageOptionId")
                        .HasColumnType("uuid");

                    b.Property<long>("PriceMinor")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("AthleteUserId");

                    b.HasIndex("PackageOptionId");

                    b.HasIndex("AthleteUserId", "PackageOptionId")
                        .IsUnique();

                    b.ToTable("AthletePackagePrices", (string)null);
                });

            modelBuilder.Entity("BeyondMovement.Modules.Packages.Domain.PackageOption", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("ArchivedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("CoachId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<long>("DefaultPriceMinor")
                        .HasColumnType("bigint");

                    b.Property<bool>("IsArchived")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<int>("Sessions")
                        .HasColumnType("integer");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Version")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("CoachId", "IsArchived");

                    b.ToTable("PackageOptions", (string)null);
                });

            modelBuilder.Entity("BeyondMovement.Modules.Packages.Domain.PackageOptionFeature", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Code")
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)");

                    b.Property<Guid>("PackageOptionId")
                        .HasColumnType("uuid");

                    b.Property<int>("Position")
                        .HasColumnType("integer");

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("Id");

                    b.HasIndex("PackageOptionId", "Code")
                        .IsUnique()
                        .HasDatabaseName("IX_PackageOptionFeatures_OneOfEachCodePerOption")
                        .HasFilter("\"Code\" IS NOT NULL");

                    b.HasIndex("PackageOptionId", "Position")
                        .IsUnique();

                    b.ToTable("PackageOptionFeatures", (string)null);
                });

            modelBuilder.Entity("BeyondMovement.Modules.Packages.Domain.PurchasedPackage", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("AthleteProfileId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("CoachId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Currency")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("character varying(3)");

                    b.Property<DateOnly?>("EndDate")
                        .HasColumnType("date");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Notes")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<Guid?>("PackageOptionId")
                        .HasColumnType("uuid");

                    b.Property<long>("PricePaidMinor")
                        .HasColumnType("bigint");

                    b.Property<DateOnly>("StartDate")
                        .HasColumnType("date");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<int>("TotalSessions")
                        .HasColumnType("integer");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("UsedSessions")
                        .HasColumnType("integer");

                    b.Property<uint>("Version")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.PrimitiveCollection<string[]>("_includedFeatures")
                        .IsRequired()
                        .HasColumnType("character varying(40)[]")
                        .HasColumnName("IncludedFeatures");

                    b.HasKey("Id");

                    b.HasIndex("AthleteProfileId")
                        .IsUnique()
                        .HasDatabaseName("IX_PurchasedPackages_OneActivePerAthlete")
                        .HasFilter("\"Status\" = 'Active'");

                    b.HasIndex("PackageOptionId");

                    b.HasIndex("AthleteProfileId", "CreatedAtUtc");

                    b.ToTable("PurchasedPackages", null, t =>
                        {
                            t.HasCheckConstraint("CK_PurchasedPackages_Dates", "\"EndDate\" IS NULL OR \"EndDate\" >= \"StartDate\"");

                            t.HasCheckConstraint("CK_PurchasedPackages_Price", "\"PricePaidMinor\" >= 0");

                            t.HasCheckConstraint("CK_PurchasedPackages_TotalSessions", "\"TotalSessions\" > 0");

                            t.HasCheckConstraint("CK_PurchasedPackages_UsedSessions", "\"UsedSessions\" >= 0 AND \"UsedSessions\" <= \"TotalSessions\"");
                        });
                });

            modelBuilder.Entity("BeyondMovement.Modules.Scheduling.Domain.BookingOperation", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("AthleteProfileId")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("CompletedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("IdempotencyKey")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<Guid?>("SessionId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("CreatedAtUtc");

                    b.HasIndex("SessionId");

                    b.HasIndex("AthleteProfileId", "IdempotencyKey")
                        .IsUnique();

                    b.ToTable("SchedulingBookingOperations", (string)null);
                });

            modelBuilder.Entity("BeyondMovement.Modules.Scheduling.Domain.CalendlyReconciliationRun", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("CancelledCount")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("CompletedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("CreatedCount")
                        .HasColumnType("integer");

                    b.Property<string>("Error")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<int>("FlaggedCount")
                        .HasColumnType("integer");

                    b.Property<int>("RemoteCount")
                        .HasColumnType("integer");

                    b.Property<DateTime>("StartedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("UpdatedCount")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("StartedAtUtc");

                    b.ToTable("CalendlyReconciliationRuns", (string)null);
                });

            modelBuilder.Entity("BeyondMovement.Modules.Scheduling.Domain.CalendlyUnmatchedBooking", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid?>("AssignedAthleteProfileId")
                        .HasColumnType("uuid");

                    b.Property<string>("CalendlyEventTypeUri")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("CalendlyEventUri")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("CalendlyInviteeUri")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<DateTime>("DiscoveredAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("InviteeEmail")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("Reason")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<DateTime?>("ResolvedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("CalendlyInviteeUri")
                        .IsUnique();

                    b.HasIndex("ResolvedAtUtc", "DiscoveredAtUtc");

                    b.ToTable("CalendlyUnmatchedBookings", (string)null);
                });

            modelBuilder.Entity("BeyondMovement.Modules.Scheduling.Domain.CalendlyWebhookEvent", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("Attempts")
                        .HasColumnType("integer");

                    b.Property<string>("EventType")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("IdempotencyKey")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<string>("LastError")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<string>("PayloadJson")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<DateTime?>("ProcessedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("ReceivedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.HasKey("Id");

                    b.HasIndex("IdempotencyKey")
                        .IsUnique();

                    b.HasIndex("Status", "ReceivedAtUtc");

                    b.ToTable("CalendlyWebhookEvents", (string)null);
                });

            modelBuilder.Entity("BeyondMovement.Modules.Scheduling.Domain.ObservationRequest", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("AthleteProfileId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("CoachId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Details")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<string>("Location")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<int>("RequestedDurationMinutes")
                        .HasColumnType("integer");

                    b.Property<DateTime>("RequestedStartUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("ResolvedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("ResolvedByUserId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("SessionId")
                        .HasColumnType("uuid");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<uint>("Version")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.HasKey("Id");

                    b.HasIndex("SessionId")
                        .IsUnique()
                        .HasDatabaseName("IX_ObservationRequests_OneRequestPerSession")
                        .HasFilter("\"SessionId\" IS NOT NULL");

                    b.HasIndex("AthleteProfileId", "CreatedAtUtc");

                    b.HasIndex("CoachId", "Status", "RequestedStartUtc");

                    b.ToTable("ObservationRequests", null, t =>
                        {
                            t.HasCheckConstraint("CK_ObservationRequests_AcceptedHasSession", "(\"Status\" = 'Accepted' AND \"SessionId\" IS NOT NULL) OR (\"Status\" <> 'Accepted' AND \"SessionId\" IS NULL)");

                            t.HasCheckConstraint("CK_ObservationRequests_Duration", "\"RequestedDurationMinutes\" BETWEEN 15 AND 1440");

                            t.HasCheckConstraint("CK_ObservationRequests_ResolvedConsistency", "(\"Status\" = 'Pending' AND \"ResolvedAtUtc\" IS NULL AND \"ResolvedByUserId\" IS NULL) OR (\"Status\" <> 'Pending' AND \"ResolvedAtUtc\" IS NOT NULL AND \"ResolvedByUserId\" IS NOT NULL)");
                        });
                });

            modelBuilder.Entity("BeyondMovement.Modules.Scheduling.Domain.SchedulingChange", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("DedupKey")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<DateTime>("OccurredAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("PublishedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("SessionId")
                        .HasColumnType("uuid");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.HasKey("Id");

                    b.HasIndex("DedupKey")
                        .IsUnique();

                    b.HasIndex("SessionId");

                    b.HasIndex("PublishedAtUtc", "OccurredAtUtc");

                    b.ToTable("SchedulingChanges", (string)null);
                });

            modelBuilder.Entity("BeyondMovement.Modules.Scheduling.Domain.Session", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("AthleteProfileId")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("AttendedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("AttendedByUserId")
                        .HasColumnType("uuid");

                    b.Property<string>("CalendlyEventTypeUri")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("CalendlyEventUri")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("CalendlyInviteeUri")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("CancelUrl")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<string>("CancellationReason")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<DateTime?>("CancelledAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("CoachId")
                        .HasColumnType("uuid");

                    b.Property<int?>("ConsumedPackagePosition")
                        .HasColumnType("integer");

                    b.Property<int>("ConsumedSessionCount")
                        .HasColumnType("integer");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("DeliveryType")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.Property<int>("DurationMinutes")
                        .HasColumnType("integer");

                    b.Property<string>("LocationOrPlatform")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("MeetingUrl")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<bool?>("ObservationDeductsSession")
                        .HasColumnType("boolean");

                    b.Property<Guid?>("PackageId")
                        .HasColumnType("uuid");

                    b.Property<string>("RescheduleUrl")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<DateTime>("ScheduledEndUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("ScheduledStartUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<uint>("Version")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.HasKey("Id");

                    b.HasIndex("CalendlyEventUri")
                        .IsUnique();

                    b.HasIndex("CalendlyInviteeUri")
                        .IsUnique();

                    b.HasIndex("PackageId");

                    b.HasIndex("AthleteProfileId", "ScheduledStartUtc");

                    b.HasIndex("CoachId", "ScheduledStartUtc", "Status");

                    b.ToTable("Sessions", null, t =>
                        {
                            t.HasCheckConstraint("CK_Sessions_Consumed", "\"ConsumedSessionCount\" IN (0, 1)");

                            t.HasCheckConstraint("CK_Sessions_ConsumedOnlyWhenResolved", "\"ConsumedSessionCount\" = 0 OR \"Status\" IN ('Attended', 'NoShow')");

                            t.HasCheckConstraint("CK_Sessions_Duration", "\"DurationMinutes\" > 0");

                            t.HasCheckConstraint("CK_Sessions_ObservationDeductsSession", "(\"DeliveryType\" = 'Observation') = (\"ObservationDeductsSession\" IS NOT NULL)");

                            t.HasCheckConstraint("CK_Sessions_PackagePositionMatchesConsumption", "(\"ConsumedSessionCount\" = 0 AND \"ConsumedPackagePosition\" IS NULL) OR (\"ConsumedSessionCount\" = 1 AND \"ConsumedPackagePosition\" > 0)");

                            t.HasCheckConstraint("CK_Sessions_TimeRange", "\"ScheduledEndUtc\" > \"ScheduledStartUtc\"");
                        });
                });

            modelBuilder.Entity("BeyondMovement.Modules.Scheduling.Domain.SessionNote", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("AuthorUserId")
                        .HasColumnType("uuid");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasMaxLength(4000)
                        .HasColumnType("character varying(4000)");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("SessionId")
                        .HasColumnType("uuid");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("SessionId", "CreatedAtUtc");

                    b.ToTable("SessionNotes", (string)null);
                });

            modelBuilder.Entity("BeyondMovement.Modules.Scheduling.Domain.SessionNoteAttachment", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("CommittedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ContentType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<long>("DeclaredSizeBytes")
                        .HasColumnType("bigint");

                    b.Property<DateTime?>("DeletionRequestedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("SessionNoteId")
                        .HasColumnType("uuid");

                    b.Property<long?>("SizeBytes")
                        .HasColumnType("bigint");

                    b.Property<int>("SortOrder")
                        .HasColumnType("integer");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("StorageKey")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<DateTime>("UploadExpiresAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("UploadedByUserId")
                        .HasColumnType("uuid");

                    b.Property<uint>("Version")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.HasKey("Id");

                    b.HasIndex("StorageKey")
                        .IsUnique();

                    b.HasIndex("Status", "UploadExpiresAtUtc");

                    b.HasIndex("SessionNoteId", "Status", "SortOrder");

                    b.ToTable("SessionNoteAttachments", null, t =>
                        {
                            t.HasCheckConstraint("CK_SessionNoteAttachments_CommittedConsistency", "(\"Status\" = 'Pending' AND \"CommittedAtUtc\" IS NULL AND \"SizeBytes\" IS NULL) OR (\"Status\" = 'Committed' AND \"CommittedAtUtc\" IS NOT NULL AND \"SizeBytes\" IS NOT NULL) OR \"Status\" = 'Deleting'");

                            t.HasCheckConstraint("CK_SessionNoteAttachments_DeclaredSize", "\"DeclaredSizeBytes\" > 0");

                            t.HasCheckConstraint("CK_SessionNoteAttachments_DeletionConsistency", "(\"Status\" = 'Deleting') = (\"DeletionRequestedAtUtc\" IS NOT NULL)");

                            t.HasCheckConstraint("CK_SessionNoteAttachments_SortOrder", "\"SortOrder\" >= 0");
                        });
                });

            modelBuilder.Entity("BeyondMovement.Modules.Athletes.Domain.AthleteProfile", b =>
                {
                    b.HasOne("BeyondMovement.Modules.Athletes.Domain.Sport", null)
                        .WithMany()
                        .HasForeignKey("SportId")
                        .OnDelete(DeleteBehavior.Restrict);
                });

            modelBuilder.Entity("BeyondMovement.Modules.Finance.Domain.PackagePurchase", b =>
                {
                    b.HasOne("BeyondMovement.Modules.Athletes.Domain.AthleteProfile", null)
                        .WithMany()
                        .HasForeignKey("AthleteProfileId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("BeyondMovement.Modules.Packages.Domain.PackageOption", null)
                        .WithMany()
                        .HasForeignKey("PackageOptionId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("BeyondMovement.Modules.Packages.Domain.PurchasedPackage", null)
                        .WithMany()
                        .HasForeignKey("PurchasedPackageId")
                        .OnDelete(DeleteBehavior.Restrict);
                });

            modelBuilder.Entity("BeyondMovement.Modules.Finance.Domain.PackagePurchaseFeature", b =>
                {
                    b.HasOne("BeyondMovement.Modules.Finance.Domain.PackagePurchase", null)
                        .WithMany("_features")
                        .HasForeignKey("PackagePurchaseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("BeyondMovement.Modules.Identity.Domain.PasswordResetToken", b =>
                {
                    b.HasOne("BeyondMovement.Modules.Identity.Domain.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("BeyondMovement.Modules.Identity.Domain.RefreshToken", b =>
                {
                    b.HasOne("BeyondMovement.Modules.Identity.Domain.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("BeyondMovement.Modules.Packages.Domain.AthletePackagePrice", b =>
                {
                    b.HasOne("BeyondMovement.Modules.Packages.Domain.PackageOption", null)
                        .WithMany()
                        .HasForeignKey("PackageOptionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("BeyondMovement.Modules.Packages.Domain.PackageOptionFeature", b =>
                {
                    b.HasOne("BeyondMovement.Modules.Packages.Domain.PackageOption", null)
                        .WithMany("_features")
                        .HasForeignKey("PackageOptionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("BeyondMovement.Modules.Packages.Domain.PurchasedPackage", b =>
                {
                    b.HasOne("BeyondMovement.Modules.Athletes.Domain.AthleteProfile", null)
                        .WithMany()
                        .HasForeignKey("AthleteProfileId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("BeyondMovement.Modules.Packages.Domain.PackageOption", null)
                        .WithMany()
                        .HasForeignKey("PackageOptionId")
                        .OnDelete(DeleteBehavior.SetNull);
                });

            modelBuilder.Entity("BeyondMovement.Modules.Scheduling.Domain.BookingOperation", b =>
                {
                    b.HasOne("BeyondMovement.Modules.Athletes.Domain.AthleteProfile", null)
                        .WithMany()
                        .HasForeignKey("AthleteProfileId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BeyondMovement.Modules.Scheduling.Domain.Session", null)
                        .WithMany()
                        .HasForeignKey("SessionId")
                        .OnDelete(DeleteBehavior.SetNull);
                });

            modelBuilder.Entity("BeyondMovement.Modules.Scheduling.Domain.ObservationRequest", b =>
                {
                    b.HasOne("BeyondMovement.Modules.Athletes.Domain.AthleteProfile", null)
                        .WithMany()
                        .HasForeignKey("AthleteProfileId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("BeyondMovement.Modules.Scheduling.Domain.Session", null)
                        .WithMany()
                        .HasForeignKey("SessionId")
                        .OnDelete(DeleteBehavior.Restrict);
                });

            modelBuilder.Entity("BeyondMovement.Modules.Scheduling.Domain.SchedulingChange", b =>
                {
                    b.HasOne("BeyondMovement.Modules.Scheduling.Domain.Session", null)
                        .WithMany()
                        .HasForeignKey("SessionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("BeyondMovement.Modules.Scheduling.Domain.Session", b =>
                {
                    b.HasOne("BeyondMovement.Modules.Athletes.Domain.AthleteProfile", null)
                        .WithMany()
                        .HasForeignKey("AthleteProfileId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("BeyondMovement.Modules.Packages.Domain.PurchasedPackage", null)
                        .WithMany()
                        .HasForeignKey("PackageId")
                        .OnDelete(DeleteBehavior.Restrict);
                });

            modelBuilder.Entity("BeyondMovement.Modules.Scheduling.Domain.SessionNote", b =>
                {
                    b.HasOne("BeyondMovement.Modules.Scheduling.Domain.Session", null)
                        .WithMany()
                        .HasForeignKey("SessionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("BeyondMovement.Modules.Scheduling.Domain.SessionNoteAttachment", b =>
                {
                    b.HasOne("BeyondMovement.Modules.Scheduling.Domain.SessionNote", null)
                        .WithMany()
                        .HasForeignKey("SessionNoteId")
                        .OnDelete(DeleteBehavior.SetNull);
                });

            modelBuilder.Entity("BeyondMovement.Modules.Finance.Domain.PackagePurchase", b =>
                {
                    b.Navigation("_features");
                });

            modelBuilder.Entity("BeyondMovement.Modules.Packages.Domain.PackageOption", b =>
                {
                    b.Navigation("_features");
                });
#pragma warning restore 612, 618
        }
    }
}
